### PR TITLE
Replace underscore with space

### PR DESCRIPTION
**Pull request by mattwr18**
Capybara syntax error

### CODE REVIEW

**Comment by idfubar** [comment]
@tansaku: Per the conversation in the 'AV102' channel on 2018/07/13 & 2018/07/14 the error has been confirmed to be the likely source of current failures observed with AV102 HW1.3; the fix is O.K. per the same consensus - but the value 'true' could be made, alternatively, 'truthy' to the same effect...

**Comment by tansaku** [comment]
thanks @mattwr18 and @idfubar - we might consider upgrading to rspec 3 syntax, but I'll get this merged

**Comment by tansaku** [comment]
of course there's a cache on the autograder so we might not see this update immediately unless I clear the cache

**Comment by tansaku** [comment]
I cleared the cache - hopefully this will work now ...

**Pull request merged**
